name: vaicu-env
channels:
- conda-forge
dependencies:
- jupyter>=1.0
- matplotlib=2.0.2
- nbstripout=0.3.1
- numpy=1.13.1
- pandas=0.20.3
- python=3.6.2
- scipy=0.19.1
- Pillow=4.0.0
- plotly>=2.0.5
- pytz>=2016.10
- nb_conda>=2.2
- nb_conda_kernels>=2.1
- boto3
